[package]
name = "polo-scraper"
version = "0.1.0"
authors = ["phreaknik <johnboydiv@gmail.com>"]
description = "This tool is cool"

[dependencies]
clap = "2.26"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
